### ISSUE TITLE
The runtime parameter of nodejs10.x is no longer supported

### ISSUE THREAD

**Issue by ChrisHarries** [GorillaStack/auto-tag#101]
I am rather perplexed as to how this is happening. I have run `git pull` to ensure I have the latest version, and I have even updated the nodejs version to 14.x within 3 cloudformation files by hand. However, I am still hitting this error when running this command
`
./deploy_autotag.sh -r eu-north-1 --s3-bucket bucket_name --release-version latest --profile dev --custom-tags '{"AutoTag_Team": "$event.requestParameters.tagSpecificationSet.items.tags"}' create`

> Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs14.x) while creating or updating functions.

**Comment by viallikavoo** [comment]
This is happening because the Cloudformation template that gets uploaded to AWS is taken from the latest release from [this](https://github.com/GorillaStack/auto-tag/blob/master/deploy_autotag.sh#L281) line 
 which still sets the 
`"Runtime": "nodejs10.x",`
I got around this issue by replacing the Runtimes in the 3 cloudformation templates by hand and then also replacing the
  [line](https://github.com/GorillaStack/auto-tag/blob/master/deploy_autotag.sh#L281) in my local to 
`    MAIN_TEMPLATE=$(cat cloud_formation/event_multi_region_template/autotag_event_main-template.json)
`
