### ISSUE TITLE
CodeS3Bucket and regions

### ISSUE THREAD

**Issue by neilhwatson** [GorillaStack/auto-tag#29]
gorillastack-autotag-releases-ca-central-1 results in "Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist".

This might be a case for a map.

Are we expect to install a stack in every region we want to monitor?

**Comment by rayj-pgi** [comment]
Hi Neil,
   I can help, you don't need to install this in every region. It will be able to see whatever you set the CloudTrail logs to output. The provided CloudFormation script enables CloudTrail for all regions. If you switch to deploying in us-east-1 it will probably work for you, I'd imagine the maintainer just hasn't put the zip file ca-central-1 yet since it is so new.

**Comment by em0ney** [comment]
Absolutely right @rayj-pgi - just haven't yet deployed to `ca-central-1`.  Will do so as part of a heap of maintenance I'm working through now
