### ISSUE TITLE
EBS Volumes not tagged

### ISSUE THREAD

**Issue by MaheshBeri** [GorillaStack/auto-tag#6]
@em0ney I was testing all resources as per your list.

Covered EC2,RDS and ELB so far all are tagged.
However EBS volumes (root and other volume) that I created with my Ec2 did not get tagged. Ec2 itself was tagged okay.
Was wondering if there is a debug option in auto tag so we get more info in Cloudwatch.

EBS volumes need to be tagged. Pl suggest.

**Comment by shashanksingh24** [comment]
Hi,
after launching the sscript in cloud formation. The resources are not tagged. Please tell me if any step i am missing.

**Comment by em0ney** [comment]
Hi there @MaheshBeri,

When an EBS volume is created as part of the creation of an instance, it doesn't have it's own event posted in CloudTrail, it is just part of the 'RunInstances' event.

I'll mark this as a feature request and get around to it eventually.  Or you could and make a pull request?

**Comment by rayj-pgi** [comment]
This is resolved with #33

**Comment by ankush-grover-3pg** [comment]
I tested today and found out the EBS volumes are not tagged whereas EC2 and RDS were tagged.

**Comment by rayj-pgi** [comment]
If your EBS volume was not tagged it is because you are not running the latest code. 

I just verified that regular ad-hoc EBS volumes ARE tagged, and I know EBS volumes that are created as part of an EC2 instance are also tagged. 

There is a list of which AWS resources this project supports in the https://github.com/GorillaStack/auto-tag#supported-resource-types.
